apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rds
  description: AWS RDS database instance
  namespace: default
spec:
  type: database
  owner: group:default/everyone
  system: your-system-name
  profile:
    type: rds
    region: us-east-1
    accountId: "051171442365"
    identifier: my-db-instance
