apiVersion: backstage.io/v1alpha1
kind: AWSEnvironment
metadata:
  name: rds-harmonix
  namespace: default
  description: AWS RDS environment for Harmonix
spec:
  region: us-east-1
  accountId: "051171442365"
  resources:
    - type: rds
      identifier: my-db-instance
